FROM openjdk:15-jdk-alpine
MAINTAINER shantadeep.das
COPY PracticeContainer-0.0.1-SNAPSHOT.jar practicecontainer-0.0.1-SNAPSHOT.jar
COPY practicecontainer-0.0.1-SNAPSHOT.jar /usr/bin/
ENTRYPOINT ["java","-jar","/practicecontainer-0.0.1-SNAPSHOT.jar"]